import { Geist, Geist_Mono, Poppins } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/layouts/Navbar";
import Footer from "@/components/layouts/Footer";

const poppins = Poppins({
  weight: ["100", "200", "400", "500", "600", "800"],
});

export const fontBangla = localFont({
  src: "../fonts/mayaboti-normal.ttf",
  // weight: ["100", "200", "400", "500", "600", "800"],
});

export const metadata = {
  title: {
    default: "Hero Kids",
    template: "%s | Hero Kids",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <header className="py-2 md:w-11/12 mx-auto">
          <Navbar />
        </header>

        <main className="py-2 md:w-11/12 mx-auto min-h-[calc(100svh-303px)]">
          {children}
        </main>

        <Footer />
      </body>
    </html>
  );
}
